package main

import "fmt"

func main() {

	arr := []string{"a", "b", "c"}
	retArr := make([]string, 0, len(arr))
	retArr = append(retArr, "d")
	fmt.Println(arr)
	fmt.Println(retArr)
}

/*
	generated by copilot

● This creates a slice with initial length and capacity.

  arr := []string{"a", "b", "c"}
  retArr := make([]string, 0, len(arr))

  Breaking it down:

  ┌───────────────────────┬────────────────────────────────────────────┐
  │ Part                  │ Meaning                                    │
  ├───────────────────────┼────────────────────────────────────────────┤
  │ make([]string, ...)   │ Create a slice of strings                  │
  ├───────────────────────┼────────────────────────────────────────────┤
  │ 0                     │ Initial length = 0 (empty, but exists)     │
  ├───────────────────────┼────────────────────────────────────────────┤
  │ len(arr)              │ Capacity = size of arr                     │
  └───────────────────────┴────────────────────────────────────────────┘

  Visual:

   Length:   0 (no elements yet)
   Capacity: len(arr) (room for len(arr) elements)

   [_ _ _ _ ]  <- 4 spaces allocated, 0 in use

  Difference from make([]string, len(arr)):

   make([]string, 0, len(arr))   // Length 0, capacity len(arr)
   make([]string, len(arr))      // Length len(arr), capacity len(arr)

  Why this matters:

   retArr := make([]string, 0, len(arr))
   retArr = append(retArr, "d")
   // No memory reallocation needed
   // because capacity was pre-allocated

  Use case: When you know the final size ahead of time,
  pre-allocate capacity to avoid repeated memory reallocations
  during append() operations.

output:
[a b c]
[d]

*/
